//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysCadCar.Mvc.App.ServiceCarroWcf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carro", Namespace="http://schemas.datacontract.org/2004/07/SysCadCar.Domain.Entity")]
    [System.SerializableAttribute()]
    public partial class Carro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SysCadCar.Mvc.App.ServiceCarroWcf.Status BloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlacaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProprietarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RenavanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlFotosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SysCadCar.Mvc.App.ServiceCarroWcf.Status Bloqueio {
            get {
                return this.BloqueioField;
            }
            set {
                if ((this.BloqueioField.Equals(value) != true)) {
                    this.BloqueioField = value;
                    this.RaisePropertyChanged("Bloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Placa {
            get {
                return this.PlacaField;
            }
            set {
                if ((object.ReferenceEquals(this.PlacaField, value) != true)) {
                    this.PlacaField = value;
                    this.RaisePropertyChanged("Placa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Proprietario {
            get {
                return this.ProprietarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ProprietarioField, value) != true)) {
                    this.ProprietarioField = value;
                    this.RaisePropertyChanged("Proprietario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Renavan {
            get {
                return this.RenavanField;
            }
            set {
                if ((object.ReferenceEquals(this.RenavanField, value) != true)) {
                    this.RenavanField = value;
                    this.RaisePropertyChanged("Renavan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlFotos {
            get {
                return this.UrlFotosField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlFotosField, value) != true)) {
                    this.UrlFotosField = value;
                    this.RaisePropertyChanged("UrlFotos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Status", Namespace="http://schemas.datacontract.org/2004/07/SysCadCar.Domain.Enun")]
    public enum Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bloqueado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoBloqueado = 0,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCarroWcf.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarro", ReplyAction="http://tempuri.org/IService1/AddCarroResponse")]
        bool AddCarro(SysCadCar.Mvc.App.ServiceCarroWcf.Carro carroAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCarro", ReplyAction="http://tempuri.org/IService1/AddCarroResponse")]
        System.Threading.Tasks.Task<bool> AddCarroAsync(SysCadCar.Mvc.App.ServiceCarroWcf.Carro carroAdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listCarro", ReplyAction="http://tempuri.org/IService1/listCarroResponse")]
        SysCadCar.Mvc.App.ServiceCarroWcf.Carro[] listCarro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/listCarro", ReplyAction="http://tempuri.org/IService1/listCarroResponse")]
        System.Threading.Tasks.Task<SysCadCar.Mvc.App.ServiceCarroWcf.Carro[]> listCarroAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewsCarro", ReplyAction="http://tempuri.org/IService1/viewsCarroResponse")]
        SysCadCar.Mvc.App.ServiceCarroWcf.Carro viewsCarro(string placa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/viewsCarro", ReplyAction="http://tempuri.org/IService1/viewsCarroResponse")]
        System.Threading.Tasks.Task<SysCadCar.Mvc.App.ServiceCarroWcf.Carro> viewsCarroAsync(string placa);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SysCadCar.Mvc.App.ServiceCarroWcf.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SysCadCar.Mvc.App.ServiceCarroWcf.IService1>, SysCadCar.Mvc.App.ServiceCarroWcf.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AddCarro(SysCadCar.Mvc.App.ServiceCarroWcf.Carro carroAdd) {
            return base.Channel.AddCarro(carroAdd);
        }
        
        public System.Threading.Tasks.Task<bool> AddCarroAsync(SysCadCar.Mvc.App.ServiceCarroWcf.Carro carroAdd) {
            return base.Channel.AddCarroAsync(carroAdd);
        }
        
        public SysCadCar.Mvc.App.ServiceCarroWcf.Carro[] listCarro() {
            return base.Channel.listCarro();
        }
        
        public System.Threading.Tasks.Task<SysCadCar.Mvc.App.ServiceCarroWcf.Carro[]> listCarroAsync() {
            return base.Channel.listCarroAsync();
        }
        
        public SysCadCar.Mvc.App.ServiceCarroWcf.Carro viewsCarro(string placa) {
            return base.Channel.viewsCarro(placa);
        }
        
        public System.Threading.Tasks.Task<SysCadCar.Mvc.App.ServiceCarroWcf.Carro> viewsCarroAsync(string placa) {
            return base.Channel.viewsCarroAsync(placa);
        }
    }
}
